### ISSUE TITLE
Generated controller code throws ArgumentError

### ISSUE THREAD

**Issue by johnmeehan** [thoughtbot/administrate#483] opened 2016-02-24 10:13 UTC
Uncommenting the generated controller code ( with the aim of scoping the results).
in this case uncommenting the index action.

``` ruby
    def index
      super
      @resources = DoorOption.all.paginate(10, params[:page])
    end
```

Results in:
![screenshot 2016-02-24 10 05 27](https://cloud.githubusercontent.com/assets/2419773/13281969/968fcc8a-dade-11e5-9bd0-43c3130ea7f4.png)

**Comment by keithlayne** [comment] 2016-02-26 02:18
I think the controller template for the generator has fallen behind the current code.  In this case, even if `paginate` wasn't throwing an error, it still probably wouldn't do what you want.  To see what I mean, look at https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L3-L15.

It's probably better to put a comment pointing to some Administrate docs on overriding controller actions than to leave the commented implementation.  It's just too hard to maintain that kind of thing in a project that is young and changing.  This issue will probably come up repeatedly, even if this particular instance is fixed.

**Comment by graysonwright** [comment] 2016-02-26 09:16
@johnmeehan and @keithlayne - thanks for pointing that out.

The template code for model controllers was written separately from the application code that drives Administrate. It was intended to act as a sample of what could be done – not as working, executable code.

In response to this issue, it seems like the generated method should definitely be executable. A good starting point, as @keithlayne mentioned, is our own [application_controller].

Feel free to submit a pull request with any code sample you think is more appropriate.

Thanks for your help!
-Grayson


[application_controller]: https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L3-L15

**Comment by carlosramireziii** [comment] 2017-02-23 20:58
@johnmeehan @keithlayne - It looks like the generated controller template has been updated to use the proper Kaminari syntax in [this commit](https://github.com/thoughtbot/administrate/commit/077f6d370b3d0eff325a3de0509aeaa21b47b632) which was merged into the current `master` branch. 

Does this solve your issue?

**Closed** 2017-03-07 18:51 UTC
