### ISSUE TITLE
`has_one?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by woniesong92** [thoughtbot/administrate#1100] opened 2018-02-18 21:22 UTC
Environments:
- ruby 2.4.2p198
- Rails 5.1.1

After a fresh install, I get this error when I run the install generator.

```
`association_type': undefined method `has_one?' for nil:NilClass (NoMethodError)
```

**Comment by FanaHOVA** [comment] 2018-02-19 14:42
@woniesong92 with fresh install do you mean Administrate or Rails? The error is raised from [here](https://github.com/thoughtbot/administrate/blob/844d7b2f879ca658a5f6d6c727a1c62e7e67ca3d/lib/generators/administrate/dashboard/dashboard_generator.rb#L105), it looks like your model association aren't properly setup. Can you post them here so we can take a look?

**Comment by bikramwp** [comment] 2018-04-13 20:38
Ping @woniesong92 ; can you post your model info so we can take a look?

**Comment by moussasarr** [comment] 2018-05-30 08:46
I am having a similar issue. @woniesong92 , did u find a solution ?

**Comment by moussasarr** [comment] 2018-05-30 08:49
This is my trace:

    `Running via Spring preloader in process 7147
/Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/dashboard_generator.rb:105:in `association_type': undefined method `has_one?' for nil:NilClass (NoMethodError)
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/dashboard_generator.rb:82:in `field_type'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:12:in `block in template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `each'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
	from /Users/moussasarr/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/moussasarr/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:122:in `block in template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/create_file.rb:46:in `identical?'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions.rb:94:in `action'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:119:in `template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/generators/named_base.rb:68:in `inside_template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/administrate-0.9.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/generators.rb:269:in `invoke'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/commands/generate/generate_command.rb:24:in `perform'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
	from /Users/moussasarr/russia/bin/rails:9:in `<top (required)>'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/moussasarr/.rvm/gems/ruby-2.3.3@russia/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
	from /Users/moussasarr/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/moussasarr/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

**Comment by moussasarr** [comment] 2018-05-30 08:51
Here is my model.rb

    `class Model < ApplicationRecord
  has_attached_file :pic, styles: { medium: "420×633!", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/
  has_many :reviews, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :favorite_models # just the 'relationships'
  has_many :favorited_by, through: :favorite_models, source: :user
  has_many :bookings
`

I am thinking it has to do with paperclip

**Comment by kjabtion** [comment] 2018-06-22 07:53
Did anyone figure out the solution to this?

**Comment by kjabtion** [comment] 2018-06-22 07:58
I was using Globalize on the model in question. If I removed `translates :name` it worked.

**Comment by FlowerWrong** [comment] 2018-08-13 12:07
the same issue. ruby 2.5.1, rails 5.2.1

**Comment by Alagaesia93** [comment] 2018-09-19 13:31
Hey! I'm having the same issue. Any plans to merge this PR?

**Comment by nickcharlton** [comment] 2018-09-19 15:36
This issue sounds like it has potentially a bunch a root causes, with `paperclip`, `acts-as-taggable-on` and others mentioned too.

Would someone with this issue be able to create an example app one of us could look at?

**Comment by Alagaesia93** [comment] 2018-09-19 15:39
I don't have any gems, just the new active storage!

**Comment by marckohlbrugge** [comment] 2019-02-16 07:00
FWIW, I'm running into the same problem. Not using Paperclip or Active Storage.

I tried removing all `belongs_to` and `has_many`, but no luck. It _might_ be related to a _string_ column called `foobar_id` which is **not** a reference to another model, but something external to the app. (e.g. _tweet_id_ when referring to Twitter's own tweet identifier).

```
rails (5.2.1.1)
administrate (0.11.0)
```

**Comment by bhtabor** [comment] 2019-02-18 12:32
In my case, the cause was the new Rails 5 attribute API. Worked by commenting those while generating the dashboard.

**Comment by tabishiqbal** [comment] 2019-04-03 03:56
Same issue but I am using ActiveStorage.

**Comment by petebytes** [comment] 2019-04-08 01:26
same issue

**Comment by nickcharlton** [comment] 2019-04-16 13:37
I've just merged #1290, which I'm hoping fixes this problem for a bunch of you.

For those with the same issue, could you try current `master` and report back? I'll close this in two weeks (by 2019-04-30), but if it's still an issue we can open another one.

**Comment by tabishiqbal** [comment] 2019-04-23 23:00
@nickcharlton just used the master branch and it seems to install however still get this error for attached images

`uninitialized constant ImageAttachmentDashboard`

**Comment by nickcharlton** [comment] 2019-04-30 11:41
Okay. I'm going to close this for now, but could you open a new issue? Perhaps with a demo app which I can have a look at?

**Closed by nickcharlton** 2019-04-30 11:41 UTC

**Comment by roberthopman** [comment] 2019-07-15 15:21
For future visitors looking for the quickfix: `gem "administrate", git: "https://github.com/thoughtbot/administrate"`

**Comment by therealrodk** [comment] 2019-10-25 19:18
I commented `acts_as_taggable_on :tags` in my model while I ran the generator and it worked fine. Just uncommented the offending lines when it was done.

**Comment by marcamillion** [comment] 2020-05-09 08:49
Confirming that @therealrodk's solution worked for me as well.

Thanks bro!
