### ISSUE TITLE
Application wide generators views don't seem to work

### ISSUE THREAD

**Issue by erdostom** [thoughtbot/administrate#557] opened 2016-04-20 15:18 UTC
ran `rails generate administrate:views` and modified `show.html.erb` and `_collection.html.erb`. Neither change was reflected in my dashboards.

**Comment by misaghshakeri** [comment] 2016-04-25 12:37
Same problem here

**Comment by davidalejandroaguilar** [comment] 2016-06-15 20:46
:+1:

**Comment by mitjok** [comment] 2016-08-30 14:53
https://github.com/thoughtbot/administrate/issues/484

**Comment by carlosramireziii** [comment] 2017-03-07 19:05
This indeed appears to be a duplicate of #484. Closing this in favor of the original issue.

**Closed by carlosramireziii** 2017-03-07 19:05 UTC
Labels: duplicate
