### ISSUE TITLE
uninitialized constant when using custom field more than 1 time

### ISSUE THREAD

**Issue by michaelimstepf** [thoughtbot/administrate#327] opened 2015-12-13 03:53 UTC
I ran into a strange error when using a same custom field more than 1 time in a dashboard.

This works fine:

```ruby
# app/dashboards/some_dashboard.rb
ATTRIBUTE_TYPES = {
  gender: Field::Select.with_options(options: ['male','female']), 
}

# app/fields/select.rb
require "administrate/fields/base"
class Select < Administrate::Field::Base
end

# app/views/fields/select/_form.html.erb
<%= f.label field.attribute %>
<%= f.select field.attribute, options_for_select(field.send(:options)[:options], field.data), { include_blank: true } %> # UGLY HACK TO ACCESS PROTECTED field.options METHOD
```

This returns an `uninitialized constant Administrate::Field::Select` error:

```ruby
# app/dashboards/some_dashboard.rb
ATTRIBUTE_TYPES = {
  gender: Field::Select.with_options(options: ['male','female']),
  role: Field::Select.with_options(options: ['manager','intern']),
}

# app/fields/select.rb
require "administrate/fields/base"
class Select < Administrate::Field::Base
end

# app/views/fields/select/_form.html.erb
<%= f.label field.attribute %>
<%= f.select field.attribute, options_for_select(field.send(:options)[:options], field.data), { include_blank: true } %> # UGLY HACK TO ACCESS PROTECTED field.options METHOD
```

**Comment by graysonwright** [comment] 2015-12-15 07:24
@michaelimstepf - I think you should change `Field::Select` to `Select` in both places.

It looks like this is a duplicate of #280, but feel free to re-open if that doesn't solve your problem.

**Closed by graysonwright** 2015-12-15 07:24 UTC

**Comment by graysonwright** [comment] 2015-12-15 08:20
Also, btw - [the changelog](https://github.com/thoughtbot/administrate/blob/master/CHANGELOG.md) is a good place to check if you see unexpected behavior after updating.

**Comment by michaelimstepf** [comment] 2015-12-15 08:50
Fixed, thanks, my bad. I'll definitely keep checking the changelog.
