### ISSUE TITLE
uninitialized constant DashboardManifest (NameError)

### ISSUE THREAD

**Issue by astamm78** [thoughtbot/administrate#146] opened 2015-11-04 18:26 UTC
Half the time when I run my `rake routes` command I get the following error:

RailsApp/config/routes.rb:26:in `block (2 levels) in <top (required)>': uninitialized constant DashboardManifest (NameError)

I've seen the `uninitialized constant DashboardManifest (NameError)` error pop up randomly when using generators as well, but the error doesn't seem to appear consistently.

**Comment by graysonwright** [comment] 2015-11-04 19:24
This seems like a duplicate of #145 - I'm closing so we can keep the discussion in one place.

**Closed by graysonwright** 2015-11-04 19:24 UTC
