### ISSUE TITLE
i18n: activerecord attributes only translates form fields

### ISSUE THREAD

**Issue by dfang** [thoughtbot/administrate#1180] opened 2018-06-23 03:17 UTC
```
zh-CN:
    activerecord:
       atrributes:
           user:
              nickname: 昵称
```

only translates form fields in  `admin/user/1/edit `,  not fields in `admins/users` and `admin/users/1`.

thanks !

**Comment by Samemura** [comment] 2018-10-24 01:01
It needs to be different definition like:
```
en:
  helpers:
    label:
      customer:
        name: Full Name
```

For the detail, please refer to https://administrate-prototype.herokuapp.com/customizing_dashboards

**Comment by kaelumania** [comment] 2020-01-22 19:55
Yes, and the model name (singular.plural via `one`/`other`) doesnt work too

**Comment by pablobm** [comment] 2020-01-23 11:44
I think this is a duplicate of https://github.com/thoughtbot/administrate/issues/1180, which I have just reopened.

**Comment by pablobm** [comment] 2020-01-23 11:44
I think this is a duplicate of https://github.com/thoughtbot/administrate/issues/625, which I have just reopened.

**Closed by pablobm** 2020-01-23 11:44 UTC
Labels: bug, i18n
