### ISSUE TITLE
Search: Field::BelongsTo always inner joined without option for a left join

### ISSUE THREAD

**Issue by skylertom** [thoughtbot/administrate#1637] opened 2020-05-06 01:05 UTC
Search: Associations are currently always inner joined, associations flagged as optional should be allowed to left joined.

Use case:
- A `Receipt` model has a `belongs_to :user, optional: true` field
- Assume we set the `ReceiptDashboard` to allow users to be searchable via the `email` field
- When searching receipts, one would expect all receipts to be searchable
  - However, there is a standard Rails `joins` (inner join) for associations 
  - The resources returned will only include receipts that have an associated user
    - This would be unexpected filtering behavior if the user did not know the implementation
  - In practice:
    - Index page w/o search term: A receipt without a user would be displayed 
    - Index page w/ a valid search term: A receipt without a user would never be displayed because of the inner join for users

[Administrate::Search class using join](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/search.rb#L112)
```
# lib/administrate/search.rb
# line 112

def search_results(resources)
  resources.
    joins(tables_to_join).
    where(query_template, *query_values)
end
```

#### Potential Solutions

- Default all associations joined to be outer joined instead of inner joined
  - Example: `joins(tables_to_join).` => `left_outer_joins(tables_to_join).`
- Include `searchable_optional: true` field for `BelongsTo`, `HasOne`, and `HasMany` associations and inner join required associations, and left join optional associations
  - Example: `joins(tables_to_join).` => `joins(standard_tables_to_join).left_outer_joins(optional_tables_to_join).`
    - `standard_tables_to_join` returns `searchable_optional` unset/false associations
    - `optional_tables_to_join` returns `searchable_optional` true associations

**Comment by pablobm** [comment] 2020-05-08 08:50
Duplicate of https://github.com/thoughtbot/administrate/pull/1581. Thanks for the detailed description!

The main issue is compatibility with Rails <5, which on the other hand may go away soon anyway. In the mean time, I think I would prefer some sort of detection over a configuration value.

Since it's duplicate, I'm going to close this and leave the conversation for the other thread.

**Closed by pablobm** 2020-05-08 08:50 UTC
