### ISSUE TITLE
View generators generates files with incorrect path

### ISSUE THREAD

**Issue by SijiaDavis** [thoughtbot/administrate#2420] opened 2023-08-23 14:12 UTC
## Describe the Bug

According to the [customize page view guide](https://administrate-demo.herokuapp.com/customizing_page_views), if we want to customize the template used for a page, we can provide our own as `/app/views/administrate/....html.erb`, and it will replace Administrate's own. I'd like to override `/app/views/administrate/application/show.html.erb`, so I used the generator command `rails generate administrate:views:show`, and it produced a file at the path `app/views/admin/application/show.html.erb` instead. I ended up having to manually rename the folder to `administrate` for the view to be correctly overridden. 

Rails version 6.0.5.1
Administrate version 0.19.0

## Steps to Reproduce

* Run `rails generate administrate:views:show`.
* Notice that the file generated is in `/app/views/admin` instead of `/app/views/administrate`.

## Expected Behavior

Running the generators should result in files generated in the `/app/views/administrate` directory.

## Actual Behavior
Running the generators results in files generated in the `/app/views/admin` directory.

**Comment by nickcharlton** [comment] 2024-01-17 14:49
This is not a bug in the generators, but rather one in the docs.

When you run the generators, we generate controllers under the `Admin` namespace and that's why the views are generated that way … in a sense, these are yours Administrate generated for you to keep and so it fits with normal Rails conventions for path loading, etc.

But also, there might be some nuances here that are worth verifying, because stuff like the `_flashes.html.erb` might be different.

**Comment by slickepinne** [comment] 2024-01-22 10:12
Hi @SijiaDavis, 
I will close this issue as I fixed the path in the documentation. It now states the correct path using the `admin` folder and not the `administrate` one. I've also verified that using the layout generator (`rails generate administrate:views:layout`) which generates the `_flashes.html.erb` works as expected. I hope this was helpful.

**Closed by slickepinne** 2024-01-22 10:12 UTC
Labels: bug
