### ISSUE TITLE
The Products page in the demo returns a 500 error

### ISSUE THREAD

**Issue by mosic** [thoughtbot/administrate#151] opened 2015-11-05 13:04 UTC
It's this page: https://administrate-prototype.herokuapp.com/admin/products

The other ones are responding normally. Nice project btw!

**Comment by graysonwright** [comment] 2015-11-05 23:34
@mosic Thanks for the heads-up! Looks like this is a duplicate of https://github.com/thoughtbot/administrate/issues/162 - let's move the conversation over there. :smile:

**Closed by graysonwright** 2015-11-05 23:34 UTC
