### ISSUE TITLE
Allow to disable sorting by a specific column

### ISSUE THREAD

**Issue by barmic12** [thoughtbot/administrate#2103] opened 2021-12-28 07:48 UTC
**What would you like to be able to do?**
I was trying to find an option to disable sorting by a specific column (virtual attribute)

**How could we go about implementing that?**
Providing a way (for example by `with_options(sortable: false) to disable sorting

Sometimes there is a need to display virtual attributes - then the sorting does not work. In this case it should not be possible to perform this action (click on the column name). Unfortunately, I didn't find a way to achieve that.

**Comment by pablobm** [comment] 2022-01-11 17:51
Hello @barmic12. At the moment there isn't a feature for this. A way around the problem would be to provide your own view for the dashboard, as described at http://administrate-demo.herokuapp.com/customizing_page_views (see under "Customizing for a specific resource"). However be careful when upgrading Administrate later, as the original template may have changed and you'd have then to update yours to match.

If you are up for a PR to provide this `sortable` option, I'd be happy to review it.

**Comment by pablobm** [comment] 2023-04-07 15:24
Duplicate of https://github.com/thoughtbot/administrate/issues/1314

**Comment by pablobm** [comment] 2023-04-07 15:25
Closing due to lack of activity

**Closed by pablobm** 2023-04-07 15:25 UTC
