### ISSUE TITLE
ActionController::UnfilteredParameters for freshly generated dashboard

### ISSUE THREAD

**Issue by SeedyROM** [thoughtbot/administrate#1615] opened 2020-04-18 23:16 UTC
* What were you trying to do?
Create a dashboard for a new model I added to my app called Host

* What did you end up with (logs, or, even better, example apps are great!)?
Upon going to the `admin/hosts` page, I get this error:
`ActionController::UnfilteredParameters in Admin::Hosts#index`
`unable to convert unpermitted parameters to hash`

The error is only coming from the index, peeking into the very unhelpful stacktrace you can see something with how administrate is generating links?
```
rails (91a848f04df8) actionpack/lib/action_controller/metal/strong_parameters.rb:273:in `to_h'
rails (91a848f04df8) actionpack/lib/action_controller/metal/strong_parameters.rb:832:in `convert_parameters_to_hashes'
rails (91a848f04df8) actionpack/lib/action_controller/metal/strong_parameters.rb:829:in `block in convert_parameters_to_hashes'
rails (91a848f04df8) activesupport/lib/active_support/hash_with_indifferent_access.rb:324:in `transform_values!'
rails (91a848f04df8) activesupport/lib/active_support/hash_with_indifferent_access.rb:324:in `block in transform_values'
rails (91a848f04df8) activesupport/lib/active_support/hash_with_indifferent_access.rb:324:in `tap'
rails (91a848f04df8) activesupport/lib/active_support/hash_with_indifferent_access.rb:324:in `transform_values'
rails (91a848f04df8) actionpack/lib/action_controller/metal/strong_parameters.rb:828:in `convert_parameters_to_hashes'
rails (91a848f04df8) actionpack/lib/action_controller/metal/strong_parameters.rb:271:in `to_h'
rails (91a848f04df8) actionpack/lib/action_dispatch/routing/url_for.rb:179:in `full_url_for'
rails (91a848f04df8) actionpack/lib/action_dispatch/routing/url_for.rb:170:in `url_for'
rails (91a848f04df8) actionview/lib/action_view/routing_url_for.rb:93:in `url_for'
rails (91a848f04df8) actionview/lib/action_view/helpers/url_helper.rb:202:in `link_to'
administrate (0.13.0) app/views/administrate/application/_collection.html.erb:31
```
Here's the source code for the dashboard is [here](https://pastebin.com/idvP8JKkl)
I've made some changes to the original model since it only doesn't work for the index, but it never worked. Even the moment after running `rails g administrate:dashboard`.

If you use the inspector in the error console and go to the `convert_parameters_to_hashes` call the value of `value` is this `<ActionController::Parameters {"order"=>:id, "direction"=>:asc} permitted: false>` which seems off. It seems like it's somehow not permitting the order of the parameter? All my other dashboards are working fine, so is it just because I named this host? haha

* What versions are you running?
  - Rails 6.0.2.2
  - administrate 0.13.0

**Comment by SeedyROM** [comment] 2020-04-19 00:47
If you've come this far, turns out just don't name your model Host and everything works great!

**Comment by pablobm** [comment] 2020-04-21 05:34
Perhaps a gem that you use is causing a conflict of some sort? I'm not able to see the pastebin any more, so I can't tell if there's something with the dashboard.

(Closing as it looks like it's not a bug).

**Closed by pablobm** 2020-04-21 05:34 UTC
Labels: bug

**Comment by hirokihokari** [comment] 2021-07-28 18:49
I can't use "Host"?

**Comment by pablobm** [comment] 2021-08-08 05:04
Uh, I think you are right. I can reproduce now. I'll have to look into it.
