### ISSUE TITLE
Error: Please use symbols for polymorphic route arguments.

### ISSUE THREAD

**Issue by esmyllyaho90** [thoughtbot/administrate#2191] opened 2022-05-10 16:41 UTC
ArgumentError Please use symbols for polymorphic route arguments.

I get this error trying to manually add the button example code from (https://github.com/SourceLabsLLC/administrate_exportable) docs:

```
<div>
  <%= link_to(
    'Export',
    [:export, namespace, page.resource_name.to_s.pluralize, sanitized_order_params(page, :id).to_h.merge(format: :csv)],
    class: 'button'
  ) if valid_action?(:export) %>
</div>
```

I'm using:
administrate 0.17
administrate_exportable 0.5
rails 7.0.1
ruby 3.0.3

**Comment by pablobm** [comment] 2022-06-23 10:10
I think this is not an issue with Administrate, but with Rails.

Reading the original issue filed with Rails (see https://github.com/rails/rails/issues/42157), it appears that they are trying to avoid a behaviour within ActionPack where a `redirect_to(["some_string"])` would result in a `redirect_to(some_string_url)` (if I understand correctly).

In your specific case, I think the problem might be with the "pluralize". Perhaps if you tried to turn that string into a symbol (`page.resource_name.to_s.pluralize.to_sym`), it may work?

The reason why it fails in your specific case despite copying from the example is that you are using a polymorphic model, where this problem exists, whereas the original example does not.

I hope that helps. I'm closing this and removing the bug tag, as I don't think that the problem is with Administrate. If you think otherwise, please let us know here.

**Closed by pablobm** 2022-06-23 10:10 UTC
Labels: bug

**Comment by andreibondarev** [comment] 2022-09-03 18:45
```
<div>
    <%= link_to(
      'Export',
      [:export, namespace.to_sym, page.resource_name.to_s.pluralize.to_sym, sanitized_order_params(page, :id).to_h.merge(format: :csv)],
      class: 'button'
    ) if valid_action?(:export) %>    
  </div>
```
^^ This should work.
