### ISSUE TITLE
problem with rerun 'rails generate administrate:install'

### ISSUE THREAD

**Issue by leunis** [thoughtbot/administrate#1003] opened 2017-10-14 17:15 UTC
Hi, 
When I rerun `rails generate administrate:install` on an existing project with extra models that I want to make available via administrate, it does not create new controllers and views.

How can I solve this

**Comment by nickcharlton** [comment] 2017-10-16 13:13
Hi @leunis!

So, to clarify, you've:

1. Run `rails g administrate:install` and built dashboards based on new models.
2. Added new models
3. Rerun `rails g administrate:install`, and expect to see these new models have dashboards?

I suspect you're seeing administrate skip because it's already been run. Usually, you'd run the `administrate:dashboard` generator to achieve this instead.

Two potential things we could do:

1. Change `install` so that it reruns regardless (which would potentially overwrite any adjustments you'd made to the existing files).
2. Hint that instead you should be running the `dashboard` generator.

What do you think?

**Comment by EskiMag** [comment] 2017-10-16 13:15
@nickcharlton Then I would say that there's a mistake in the `README.md` file. Fixing it should be enough I guess. Right?

![screen shot 2017-10-16 at 15 14 09](https://user-images.githubusercontent.com/23926/31613893-c1c3448e-b284-11e7-94a2-ed0eecc81593.png)

**Comment by nickcharlton** [comment] 2017-10-16 13:45
Ah hah! I suspect this is a regression from another change and we should restore the intended functionality.

**Comment by leunis** [comment] 2017-10-16 14:33
Hi Nick, 
The second option would be great. This is the feedback that will solve the problem and as a bonus teaches the developer how things work. 
I have read the userguide 3 times to see what i did wrong. And i totally missed this strategy. 
So this type of alert alert would have helped me a lot!

Thanks!

Martijn dekker.
06-44584411

**Comment by nickcharlton** [comment] 2017-10-29 16:00
I wasn't happy enough with what I'd understood with this issue, so I took some time to delve in and remind myself how the generators work.

The routes generator is really what's at play here, but the way it works isn't very smart. Inside `administrate:install`, `administrate:routes` is called when there's no existing resources in the `admin` namespace and then creates them. `administrate:dashboard` is called based on the admin resources. This explains why when you rerun `install` nothing appears to happen (as `routes` is never called, no new resources appear for `dashboard` to be run.

The bit where `routes` isn't very smart, is [where it only inserts the routes again][1] after being called. [We're protecting against this][2] because of that. I think it should be inserting into the existing `namespace :admin` block and there's #720 which is looking into this.

I've opened #1018 to remove the line from the documentation so it'll help others and opened #1019 so that we can look at an `install` generator that can be rerun as originally intended.

Finally, I'm going to close this one as a half-solution is the documentation fix and the real solution can be tracked elsewhere.

[1]: https://github.com/thoughtbot/administrate/blob/967506a3694037b2451d67f4efa6c73ef7c2f2a0/lib/generators/administrate/routes/routes_generator.rb#L11
[2]: https://github.com/thoughtbot/administrate/blob/967506a3694037b2451d67f4efa6c73ef7c2f2a0/lib/generators/administrate/install/install_generator.rb#L12

**Closed by nickcharlton** 2017-10-29 16:00 UTC
