### ISSUE TITLE
Not able to hide attributes on dashboards 

### ISSUE THREAD

**Issue by DhanashreeDorage** [thoughtbot/administrate#2024] opened 2021-07-26 20:00 UTC
* What were you trying to do?
   - On user Dashboard want to hide some fields like encryplted_Password
* What did you end up with (logs, or, even better, example apps are great!)?
   
![image](https://user-images.githubusercontent.com/12697581/127051037-1e0672b2-c822-4877-a952-88eb110f8001.png)

* What versions are you running?
  - Rails
       Rails 6.1.4
  - administrate
       administrate (0.16.0)

**Comment by pablobm** [comment] 2021-07-27 17:36
Unfortunately, this is not enough information for us to see what's wrong. Still, I'm going to hazard a guess: you removed `encrypted_password` from `UserDashboard::ATTRIBUTE_TYPES`, but left it in other lists like `UserDasboard::COLLECTION_ATTRIBUTES`. If this is the case, please see the documentation at https://administrate-prototype.herokuapp.com/customizing_dashboards for information on how to customize dashboards.

I'm going to close this for now, but please let us know if the problem is different and you can provide more information.

**Closed by pablobm** 2021-07-27 17:36 UTC
Labels: bug
