### ISSUE TITLE
Sharing template of ""collection" between index page and has_many show  page

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2370] opened 2023-04-25 02:54 UTC
https://administrate-demo.herokuapp.com/admin

**Comment by jubilee2** [comment] 2023-04-25 02:55
it's works in private mode

**Comment by jubilee2** [comment] 2023-04-25 12:56
@pablobm my session maybe broken
what I did is click the became button in customer show pages.
i believed that buttons should not be here
<img width="1401" alt="Screen Shot 2023-04-25 at 7 48 12 AM" src="https://user-images.githubusercontent.com/5558405/234281890-0edfe3e7-e62e-4329-bac8-9b5b352e428e.png">

**Comment by pablobm** [comment] 2023-04-25 13:57
You are right, something's off. Thank you for reporting.

**Comment by jubilee2** [comment] 2023-04-26 04:21
I think the problem is that the template uses the same resource as the parent for the has_many field. 
[    "collection",](https://github.com/thoughtbot/administrate/blob/b0fad736134bb1e47e5f5eb17f3a73640df010bf/app/views/fields/has_many/_show.html.erb#L25)

**Comment by pablobm** [comment] 2023-07-14 10:20
I have been looking into this. It's a tricky one, not just in terms of code but more importantly in terms of functionality. We need to put on our Product Manager hats and think of what we want to offer here.

We have a resource `Customer` for which we want to render a custom collection template. The bug here is that other collections for other resources in the `Customer` show page (present as `HasMany` fields) also use the custom collection template intended only for `Customer`.

From a functionality point of view, the "obvious" fix here is to ensure that each resource type should use its own collection type. Cool. But we have to think about the different variations of this pattern and make sure that our solution caters for all of them.

These are template variations that I foresee users wanting to customise:

- Resource collection on the resource's own index page (the basic one).
- Any "has many" collection on any resource's show page (a "has many" template different from the one used in index pages).
- The "has many" collection of a specific resource on any resource's show page (the "has_many" template of `Customer` in any show page)
- Any "has many" collection on the show page of a specific resource (all the "has_many" templates in a `Customer` show page)
- A specific "has many" collection on the show page of a specific resource (the "has many" template for `Order` when it appears in the `Customer` show page).
- Generalisation to other field types, possibly with some sort of inheritance mechanism. Eg: has_many_variation or nested_has_many to try a template of its own field type, then fall back on the has_many template, all while respecting the above variations!

## High-level view of the code
I found it useful at this point to see where Rails expects to find partial templates. For example, if instead of `collection_header_actions` I change the template to render `foo`, I get this error:
```
# ActionView::MissingTemplate:
#   Missing partial
       admin/customers/_foo
       admin/application/_foo
       administrate/application/_foo
    with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}.
#
#   Searched in:
#     * "$ROOT/spec/example_app/app/views"
#     * "$GEMS/administrate-field-image-1.2.0/app/views"
#     * "$ROOT/app/views"
#     * "$GEMS/kaminari-core-1.2.2/app/views"
```

This shows us that there are two "levels" of where to find the templates: the specific template names (listed under `Missing Partial:`), and the directory paths where Rails looks for template files (listed under `Searched in:`). Plus details like locale, formats, handlers, which we'll have to make sure not to break either.

Back to `collection_header_actions`, this is where Rails looks for the partial when rendering a collection of customers on the customers index page: 
```
Partials:
- admin/customers/_collection_header_actions
- admin/application/_collection_header_actions
- administrate/application/_collection_header_actions
Paths:
- "$ROOT/spec/example_app/app/views"
- "$GEMS/administrate-field-image-1.2.0/app/views"
- "$ROOT/app/views"
- "$GEMS/kaminari-core-1.2.2/app/views"
```

Let's not thing about the `Paths:` list for now as I think those are ok as they are (shout if you think otherwise!) I'm going to focus on the `Partials:` list.

Now, let's say we want to improve this list to allow all the variations I listed above. Where should Rails look for partials when asked to render `collection_header_actions` for a `Customer.has_many :orders`?
```
Partials:
- admin/customers/has_many/orders/_collection_header_actions
- admin/customers/has_many/_collection_header_actions
- admin/has_many/orders/_collection_header_actions
- admin/orders/_collection_header_actions
- admin/application/_collection_header_actions
- admin/has_many/_collection_header_actions
- administrate/application/_collection_header_actions
```

So far, does this make sense? Please shout if you need clarification, or if you think it should be different.

## Implementation
I've been experimenting with `ActionView::LookupContext` (available in views as `lookup_context`). My current intuition is that we can use it to implement our own `render` helper that will look for templates in the way we want. This isn't going to be simple! I wish there was another way to do this, but I'm running out of other ideas after kicking Rails's tires for a bit.

I've been able to do something like this:
```
locations = %W[admin/customers admin/application administrate/application]
template = lookup_context.find("collection", locations, true)
# With `template` an instance of `ActionView::Template`
```

Then we need to actually render that template, for which I believe we'd have to use `view_renderer` (still investigating). There's some information at https://medium.com/rubyinside/disassembling-rails-template-rendering-2-a99214c6fde8, but there's some additional digging to do.

OK, that's me for today. Let's see if I can do a bit more of this next week.

**Comment by pablobm** [comment] 2023-07-14 12:52
Actually, I have realised that this is a duplicate of https://github.com/thoughtbot/administrate/issues/2049. I'm going to close this one and move the detailed comment above, so as to have all information in the same place.

**Closed by pablobm** 2023-07-14 12:52 UTC
Labels: bug, views-and-styles
