### ISSUE TITLE
Dependency on bourbon not listed

### ISSUE THREAD

**Issue by pedantic-git** [thoughtbot/administrate#615] opened 2016-06-22 15:43 UTC
After upgrading to administrate 0.2.2 (from 0.2.0) my app started throwing:

```
File to import not found or unreadable: bourbon.
[snip]
./app/views/layouts/application.html.haml:8:in `_app_views_layouts_application_html_haml___2930206960703904785_47038691733580'
```

This was fixed by adding the 'bourbon' gem to my Gemfile, but I feel it should properly be included in administrate's dependencies instead.

**Comment by fourcolors** [comment] 2016-09-20 19:49
Thanks @pedantic-git I just ran into this issue today and was trying to figure out why paths from my images were not there. This saved me some time 👍

**Comment by pedantic-git** [comment] 2016-09-21 08:33
@fourcolors It looks like it's fixed in the master branch now, so hopefully in the next release we can drop this.

**Comment by fourcolors** [comment] 2016-09-21 20:58
@pedantic-git Thanks again!

**Comment by JoelQ** [comment] 2016-10-07 14:57
@danbee can you confirmed that this has been fixed? If so I think we can close the issue.

**Comment by pcantrell** [comment] 2016-10-10 21:09
It’s not currently fixed on the master branch.

**Comment by pkoch** [comment] 2016-10-19 11:20
I solved this by adding `require 'bourbon'` in my `config/application.rb`.

What would be the right way to fix this on master?

**Comment by seraph** [comment] 2016-10-28 21:08
I just encountered this bug on Rails 5, fresh app with a single model. I resolved it by adding bourbon to my Gemfile directly, and bundling.

**Comment by pkoch** [comment] 2016-10-31 11:19
To fix this, either put bourbon in your Gemfile or `require 'bourbon'` somewhere in your initializers. Something like kpheasey's patch should eventually be added to administrate to fix this for good.

**Closed** 2016-12-20 03:01 UTC
Labels: bug

**Comment by brandonweiss** [comment] 2017-02-19 04:42
@nickcharlton No new release?

**Comment by ACPK** [comment] 2019-08-02 17:01
@nickcharlton - This issue still seems to be a problem for a new install that uses the latest version (0.0.11).
