### ISSUE TITLE
Scope sort and order params by association

### ISSUE THREAD

**Issue by micapam** [thoughtbot/administrate#471] opened 2016-02-16 02:55 UTC
Repro steps:
- Given two models, Foo and Bar, where Foo has many Bars
- Bar has a 'name' attribute
- Dashboards set up with has many relationship defined
- Browse to show page for an instance of Foo that has three Bar instances
- Observe the order of the three Bar instances, then click on the 'name' header
- Page reloads with query string modified e.g. direction=asc&order=name

Expected:
- Bar instances sorted by name

Actual: 
- Sort order is unchanged

Thoughts: 
- Given that it's possible to have multiple has many associations, it's not enough for the query string to specify 'direction' and 'order'. These arguments need to be scoped to the association e.g. 'order[bar]' or 'bar[order]' or something like that.

**Comment by micapam** [comment] 2016-02-16 02:56
(Please let me know your thoughts & preferences on that final point - how to handle multiple has many relationships - and I'd be happy to create a PR to fix this.)

**Comment by micapam** [comment] 2016-03-03 00:40
Ready & willing to fix this myself & raise a PR. Just want core team's input on preferred naming for params. Anyone?

**Comment by graysonwright** [comment] 2016-03-08 06:36
Hey, @micapam - sorry for the late response. I think naming the params `order[bar]` and `direction[bar]` is a good approach. Feel free to open a PR; otherwise I'll figure out a milestone for this.

**Comment by akirsch** [comment] 2016-05-30 13:19
Hello.
Short question. Is this problem on the way to solve?
I run in this problem in my current project.

Thx.

**Comment by getaaron** [comment] 2016-07-14 00:31
Is this a dupe of https://github.com/thoughtbot/administrate/issues/265?

**Closed** 2017-12-19 23:01 UTC
Labels: enhancement, help wanted
