### ISSUE TITLE
Overriding the index method on a controller 

### ISSUE THREAD

**Issue by tylrd** [thoughtbot/administrate#320] opened 2015-12-11 15:09 UTC
I'm trying to display all the users that aren't administrators in my users dashboard.

``` ruby
def index
  super
  @resources = User.where(admin: false).page(params[:page])
end
```

This is essentially from the boilerplate provided. The collections partial is rendering first and then the index method is being hit - it doesn't pass my `@resources` into the partial. Anything I am missing?

**Comment by graysonwright** [comment] 2015-12-12 18:23
Hey, @taylor-d.

[Here's the default code for the `index` action][index]. As you can see, the resources are populated by the `Administrate::Search` object, and are passed to the views through local variables.

If you want to override the resources that are passed to the views, you'll have to overwrite the entire method - try copying the entire `index` action into your controller, and editing line 5.

I'm starting to question whether local variables are really the best option - they came up in #318 as well. It seems like they might make it difficult to override behavior like this.

[index]: https://github.com/thoughtbot/administrate/blob/8d30944123662e08208d101c5cbf0c71d27c2b68/app/controllers/administrate/application_controller.rb#L3-L15

**Comment by coneybeare** [comment] 2015-12-22 22:33
I came across this again today as well as in #318 with a scenario of having a logged in user only allowed to access certain elements in the collection. I can use the cancan gem on the front end to remove buttons and links and protect urls, but there should be an easier way to edit the finder for the collection than overriding the entire method.

Luckily, arel was made for this kind of thing. Why not provide a simple hook at the end of your resources arel chain to allow the dashboard to tack on a clause? Something like

````ruby
    ...
    resources = resources.page(params[:page]).per(records_per_page)
    resources = finder_chain_additions(resources)
    page = Administrate::Page::Collection.new(dashboard, order: order)
    ...


    def finder_chain_additions
        resources
    end
````

This would allow any `DashboardController` subclass a way to do things like authorization, custom filtering etc...

Thoughts?

**Comment by codemang** [comment] 2016-01-08 22:30
I was just trying to solve this very same problem. To me this is an absolutely critical feature to support if I am to adopt Administrate for my needs, do you know if this will be addressed in any upcoming releases?

**Comment by joshco** [comment] 2016-02-10 00:33
+1  critical feature

**Comment by pferdefleisch** [comment] 2016-08-06 11:47
I don't think this is a critical feature because as shown above, it's just Ruby and you can just pull the body of the `Administrate::ApplicationController#index` method into the commented out index method in the generated dashboard controller.

The issue here, which @graysonwright didn't address above, is that the comments lie. The comments show you a technique that just doesn't work. The comments shouldn't lie.

So, to move forward, should we change the comments to being something correct or do we have to extract a helper method or show a different technique?

If we're going to call super, rendering needs to be taken care of in a different way. Any suggestions of how to do this? Could resources be a method that we override?

Here is some sample code that works but would probably break a bunch of apps

```ruby
# app/controllers/administrate/application_controller.rb
module Administrate
  class ApplicationController < ActionController::Base
    def index
      page = Administrate::Page::Collection.new(dashboard, order: order)

      render locals: {
        resources: resources,
        search_term: search_term,
        page: page,
      }
    end

  # ...

  private

    def resources
      r = Administrate::Search.new(resource_resolver, search_term).run
      r = order.apply(r)
      r.page(params[:page]).per(records_per_page)
    end

    def search_term
      params[:search].to_s.strip
    end
```

then in your controller

```ruby

    def resources
      SomeModel.some_scope.page(params[:page]).per(records_per_page)
    end

```

This is the same idea that we see in the `Administrate::ApplicationController#find_resource` method.

What do you think?

**Comment by carlosramireziii** [comment] 2017-03-02 21:08
@nickcharlton We should look into this one

**Comment by aaronsama** [comment] 2017-05-19 08:16
@pferdefleisch I can confirm that this works. You can also just put the override in your `Admin::ApplicationController < Administrate::ApplicationController`. However, to make it work I had to add `show_search_bar: show_search_bar?` to the `locals` hash.

```ruby
    def index
      page = Administrate::Page::Collection.new(dashboard, order: order)

      render locals: {
        resources:       resources,
        search_term:     search_term,
        page:            page,
        show_search_bar: show_search_bar?
      }
    end
```

**Comment by anhari** [comment] 2017-10-18 01:21
Took a stab at this in #1007 using the suggestion from @graysonwright to replace local variables with instance variables.

**Comment by masonhale** [comment] 2017-12-26 19:54
I just bumped into this issue too. I notice the default implementation has a private `scoped_resource` method. It would be very useful if that method was not private, and thus a candidate for overwriting by sub-classes. 

The end result would work very similarly to the `begin_of_association_chain` method from the [inherited_resources](https://github.com/activeadmin/inherited_resources) gem -- which worked well in my experience. This allows you to add scoping/filtering to a model, in way that gets picked up by just by index, but also show, edit, update and destroy methods.

**Comment by nickcharlton** [comment] 2018-01-16 13:55
Ah, interesting. I noticed now that @anhari's PR hadn't moved along much recently.

@masonhale Do you have any thoughts on that implementation vs. your proposed one?

**Comment by masonhale** [comment] 2018-01-16 17:34
@nickcharlton I've used inherited_resources in the past I really appreciated how it automatically handled the "normal"-case for REST-style controller method, but it also got out of the way easily and incrementally. I say incrementally because if you want to say add a filter to the data seen in the controller (say by using the [has_scope](https://github.com/plataformatec/has_scope) gem), then you could use begin_of_association_chain or end_of_association_chain to plug that in without having to override the entire controller. In the same way if you did decide to override a controller method like `update`, you could take full responsibility for the entire method, or if you wanted to just insert some logic to trigger a background update task, you could still call `update!` (a method provided by the inherited_resources gem) to have it pick up the rest of the work.

When I look at the administrate project, I see the same potential -- to provide a framework that does the simple things very easily, but that gets out of the way when you need to do something more complex. Administrate already does a good job of this with the ability to add custom field types and to override views and view partials, but I see some more work to do to bring the same level of "incremental override" to the controller layer.

I think making `scoped_resource` protected so that it exposes an API for overriding is a good step -- but realize you are creating an API, so it worth taking a step back and looking at the bigger picture.  In fact, if it worked exactly like inherited_resources I would be happy, because I already know how that works, and the API has been battle-tested and evolved so is less likely to result in churn. (I realize that the Dashboard based implementation model makes actually using inherited_resources itself probably unfeasible).

**Comment by odlp** [comment] 2018-05-25 13:15
Reading the source it looks like there's already a method which can be overridden to apply scopes for `#index`:

https://github.com/thoughtbot/administrate/blob/31852e392e945b9bf6a57a41970c93b68f34764f/app/controllers/administrate/application_controller.rb#L7

If you override `#scoped_resource` then you can apply scopes as required. Here's the default implmentation:
https://github.com/thoughtbot/administrate/blob/31852e392e945b9bf6a57a41970c93b68f34764f/app/controllers/administrate/application_controller.rb#L121-L123

For @tylrd's case that'd be:

```ruby
def scoped_resource
  User.where(admin: false) # or resource_class.where(admin: false)
end
```

**Comment by vasco** [comment] 2018-09-15 22:26
I think the solution provided by @odlp completely solves the use case and should be a matter of updating the comments in the template https://github.com/thoughtbot/administrate/blob/master/lib/generators/administrate/dashboard/templates/controller.rb.erb to document that solution/example.

**Comment by thecalliopecrashed** [comment] 2019-05-20 19:04
Nice! It looks like this has been merged in.
Thank you, @odlp and @vasco !

**Closed by thecalliopecrashed** 2019-05-20 19:04 UTC
Labels: enhancement
