### ISSUE TITLE
Appraisal prevents Bundler cache from working on Circle CI

### ISSUE THREAD

**Issue by dgmstuart** [thoughtbot/administrate#1774] opened 2020-09-20 01:04 UTC
EDIT: Appraisal seems to clearly be the culprit here - with it the bundle steps take over 6 minutes, without it they take less than a second. This has a Huge effect on the build time,

* What were you trying to do?
Build a PR

* What did you end up with (logs, or, even better, example apps are great!)?
The CI build takes a long time - it spends nearly 15 minutes fetching and installing gems, over two `bundle install` commands: https://app.circleci.com/pipelines/github/thoughtbot/administrate/956/workflows/5cf2976f-fc78-410c-bc98-0de2ef5257fb/jobs/6869/parallel-runs/0/steps/0-103
https://app.circleci.com/pipelines/github/thoughtbot/administrate/956/workflows/5cf2976f-fc78-410c-bc98-0de2ef5257fb/jobs/6869/parallel-runs/0/steps/0-109

The PR in question doesn't involve any gem changes.

The cache does seem to be configured, and Circle seems to be saying that it's fetching from the cache. I'm not very familiar with Circle CI, but on Travis when the bundle is cached, the `bundle install` step is less than a second. 

Is there something misconfigured here, or is this some quirk of testing a gem on CI?

**Comment by nickcharlton** [comment] 2020-09-21 10:57
I _think_ it's because Appraisal is breaking the cache, so we might be restoring something that's broken and so bundler subsequently replaces it again.

I'd tried to work on making Appraisal cache it's dependencies in #1549, but I don't think the feature I added to Appraisal quite works how I'd wanted.

A way to test this might be to remove mentions of Appraisal from the CI steps on a branch and see if subsequent builds use the cache correctly.

**Comment by dgmstuart** [comment] 2020-09-21 11:40
I made a PR to see if I can test it: https://github.com/thoughtbot/administrate/pull/1775

**Comment by dgmstuart** [comment] 2020-09-21 13:17
@nickcharlton LOL yes, Appraisal is definitely the issue: 
First build without appraisal - Bundle install takes 6m 27s:
https://app.circleci.com/pipelines/github/thoughtbot/administrate/960/workflows/3e230ef7-d7c4-4139-b192-80b41009460c/jobs/6878

Second build without appraisal - Bundle install takes 0s:
https://app.circleci.com/pipelines/github/thoughtbot/administrate/962/workflows/363b85c9-06cc-447f-85b1-ce8f1f930c5a/jobs/6882

**Comment by nickcharlton** [comment] 2020-10-06 14:24
Ah hah yes. I'm not really sure how to go about solving that, as the bundled path and the Appraisal path are always going to be different …unless they can be the same? Maybe that's the answer.

Do you have any thoughts?

**Comment by dgmstuart** [comment] 2020-10-06 17:17
I'm trying to get my head around what Appraisal is - since it messes with the Gemfile I imagine the issue related to that? In which case we'd expect to see Appraisal break bundle caching anywhere it's used? 

My guess would be that the cache key for the bundle is based on hashing the Gemfile.lock: on starting a build, CI will hash the unmodified Gemfile.lock, and on a successful build it will hash the Gemfile.lock at the end, after it has been modified by Appraisal, so you'll never get a cache hit. 

Does that sound plausible?

I guess the modified Gemfile.lock is what you want to cache, since otherwise you'd install the unmodified gems?

**Comment by dgmstuart** [comment] 2020-10-06 17:26
Aha! This is CircleCI so you're defining your own cache key. If my theory is correct, then I guess you need to find a way to always generate the cache key based on the Gemfile.lock _after_ it's been modified by Appraisal?

**Comment by nickcharlton** [comment] 2020-10-06 17:44
Yeah, that just about sounds right. I'm curious how that does change the hash that's made of the `Gemfile.lock`; Appraisal doesn't touch it …or at least, I didn't think it did.

Another possibility would be to cache the combined Gemfile/Appraisals as one.

**Comment by dgmstuart** [comment] 2020-10-06 17:54
I still don't get how Appraisal works: if you're testing against 3 versions of Rails and you run `appraisal install`, does it generate 3 different Gemfile.lock files in a subdirectory, or does it modify the Gemfile.lock file in the project?

**Comment by dgmstuart** [comment] 2020-10-06 18:10
I guess either way: even though ideally we'd have one cache of gems per appraisal, Circle CI is only going to be able to support one cache of gems.

It should probably be the cache for the _unmodified_ `Gemfile.lock`, which I guess we do have since we have a regular `bundle install`.

I'm no longer confident of anything: you're right that it seems like Appraisal doesn't touch the normal Gemfile.lock

**Comment by dgmstuart** [comment] 2020-10-06 18:17
Yeah I think my theory is wrong.

Have a look at your most recent build: it looks like it loads the cache, and then reinstalls all the gems from scratch anyway:

https://app.circleci.com/pipelines/github/thoughtbot/administrate/1007/workflows/1746c565-b28c-4087-bd62-56595d7affa4/jobs/6972

I'm going to stop looking at this for today. Thanks for taking the time to reply - much appreciated.

**Comment by dgmstuart** [comment] 2020-10-06 18:24
Ok I lied I - looked a little more: looking at the build history it seems like on some builds caching is working on one version of but not the other, and on some it's working on neither.

When caching fails it takes about 11-12 mins and when it works it takes about 6-8 mins. 

It could plausibly have nothing to do with Administrate at all, but it does seem like bundle caching is generally not working on this project.

**Comment by nickcharlton** [comment] 2020-10-07 11:37
Hmm, interesting findings! Thanks for taking the time.

As I also maintain Appraisal, I'm curious too. Administrate is the main place I use it (and having a lot of dependencies, is something where it's most notable).

Appraisal generates some additional Gemfiles in `gemfiles/`, along with new `.lock` files and is broadly a wrapper around doing:

````
BUNDLE_GEMFILE=/home/circleci/administrate/gemfiles/rails60.gemfile bundle exec rake
```

A little while ago, [I added the ability to provide a bundle path][1], which I thought would allow us to cache the bundled Appraisal dependencies …but like you've been finding, I can't tell if it works or not.

[1]: https://github.com/thoughtbot/appraisal/pull/165

**Comment by dgmstuart** [comment] 2020-10-07 11:48
Yeah the issue seems to be with the original `bundle install` which happens early in the build- not the `appraisal install`?

I guess the idea is that the `appraisal install` will find that most of the gems have already been installed by the earlier `bundle install`?

I can imagine the appraisal bundle caching being a separate issue: particularly since appraisals involving rails might involve lots of gem updates? Even some with slow-running "building native extension" steps?

**Comment by dgmstuart** [comment] 2020-10-07 11:51
I guess caching the appraisal bundles on Administrate would involve adding extra caching statements to the circle CI config - one for each appraisal. But as I say: I think the main problem is with the initial `bundle install`, before appraisal gets involved

**Comment by nickcharlton** [comment] 2020-10-12 11:17
> I guess the idea is that the `appraisal install` will find that most of the gems have already been installed by the earlier `bundle install`?

Yeah, that's my expectation here, it still might take a while (as you say) but that shouldn't be too big a deal.

> But as I say: I think the main problem is with the initial `bundle install`, before appraisal gets involved

I wonder, perhaps, if the next move here is to try out different ways of caching `bundle install`. Is there a different config you've used which we could try out?

**Comment by dgmstuart** [comment] 2020-10-12 13:40
I’m afraid not: I don’t have any experience with cIrcleCI

Duncan Stuart

**Comment by nickcharlton** [comment] 2020-10-26 11:40
Thanks for taking the time to look into this.

I'm not really sure how we can progress with this one as it's a difficult one to debug, might be caused by Appraisal, but might also be caused with Circle.

I'd really like to fix this, but I think it'll become such a time sink trying to track down what is going on to the cost of having slower CI build times. I'm going to close this for now, but if someone comes along with a good insight I'd be more than happy to see us re-open and address it.

**Closed by nickcharlton** 2020-10-26 11:40 UTC
Labels: bug, dependencies, maintenance

**Comment by dgmstuart** [comment] 2020-10-26 14:44
That's fair - thanks for taking the time to have a look.
