### ISSUE TITLE
Why does show page with has_many evoke _collection to render?

### ISSUE THREAD

**Issue by xiao-wong** [thoughtbot/administrate#1183] opened 2018-06-28 06:42 UTC
I have an `Contract` model and I'm using [audited](https://github.com/collectiveidea/audited) for versions tracking.

And here are some of my codes:
```ruby
class Contract < ApplicationRecord
  audited
end

class ContractDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    id: Field::String.with_options(searchable: false),
    audits: Field::HasMany,
    # ...
  }.freeze


  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :id,
    :audits,
    # ...
  ].freeze
end
```

When I visit contract show page, it throws an error:

```
NoMethodError in Admin::Contracts#show
Showing <APP_PATH>/app/views/admin/contracts/_collection.html.erb where line #66 raised:
undefined method `admin_audited_audit_path' for #<#<Class:0x00007fa608d3a468>:0x00007fa608f9f7f8>
```

<img width="1028" alt="screen shot 2018-06-28 at 2 36 50 pm" src="https://user-images.githubusercontent.com/38643304/42017193-c11f8770-7ae0-11e8-8f29-dc7bbb290736.png">

```
Trace of template inclusion: /Users/xiao.wang/.rvm/gems/ruby-2.5.1/gems/administrate-0.10.0/app/views/fields/has_many/_show.html.erb, app/views/admin/contracts/show.html.erb
```

I didn't create routes for audits, and I don't think I should.

My question is that I'm visiting a show page of Contract, why does it call contract/_collection to render?
Then I looked at my other show pages, I found that it will call _collection template to render if the resource has a HasMany field in show page.

**Comment by brunitob** [comment] 2018-08-15 03:16
any progress on this?

**Comment by purinkle** [comment] 2019-08-13 07:39
@xiao-wong, is this still an issue for you?

**Comment by pablobm** [comment] 2020-02-07 09:53
From what I see, it's trying to render a link to an action that is not handled by the app. I think that the problem is a missing `<% if show_action? :show, resource %>`.

Some of these `show_action?`/`valid_action?` checks are missing in the templates. This specific one was added since this bug was created, so I think this is now fixed. I'm closing this issue.

Please let us know if you encounter other instances of this!

**Closed by pablobm** 2020-02-07 09:53 UTC
