### ISSUE TITLE
How to NOT cache SelectField options

### ISSUE THREAD

**Issue by hudadiaz** [thoughtbot/administrate#1466] opened 2019-11-14 05:10 UTC
* What were you trying to do?
```
    post_ids: SelectField.with_options(
      multiple: true,
      collection: Post.ids
    )
```
* What did you end up with (logs, or, even better, example apps are great!)?

When I create a post, the select option does not change. It would exclude the new post id.
When I destroy a post, the select option does not change. It would include the old post id.

* What versions are you running?
  - Rails 6.0.0
  - administrate `git: 'https://github.com/thoughtbot/administrate'`

Note: the model for the dashboard is a `RailsSettings::Base`

ref https://github.com/ledermann/rails-settings/issues/101

**Comment by GeoffAbtion** [comment] 2019-11-14 08:09
This is not a bug, this is how it is supposed to work.

What you seem to want is a `DynamiclyUpdatingSelectField` that uses some javascript to fetch the updated list of Post ids.

However you do it it's going to be more complicated than just rendering the list of selectable options one time.

**Comment by hudadiaz** [comment] 2019-11-14 15:05
To clarify, I don't expect it to change dynamically. I expect it to include or exclude the changes when the page is refreshed.

**Comment by dylnclrk** [comment] 2019-11-14 19:23
Warning: I'm not that knowledgeable about administrate. But I ran in to something similar on a custom field I had implemented. 

I think the issue is that dashboards are interpreted at deploy. So if you have a query in the definition of `ATTRIBUTE_TYPES`, it will be run when the constant is set in the class definition, and won't update as more `Post`s are created. 

Luckily, a lot of queries return an ActiveRecord Relation, which can be refreshed when (or deferred until) it comes time to actually use the values in it. Administrate probably has some code that does this when it comes time to render the field.

However, in this case, your query `Posts.ids` returns an `Array` of numbers, which cannot be reloaded, unlike the activerecord relation returned by `Posts.all`.

In my case, I (lazily) fixed it by wrapping the queries in a lambda. Since they were custom fields, it was easy enough to tweak the field to expect a lambda instead of an array.  However, I'm not sure what I'd do in this case. 

If you can't get away with using one of Administrate's association fields, like `has_many`. And using `posts` instead of `posts_ids` to edit this association (which would probably work out of the box). I think you may have to subclass SelectField or build a custom field.

**Comment by bekicot** [comment] 2020-03-30 08:52
You can use proc /  lambda
```
 post_ids: SelectField.with_options(
      multiple: true,
      collection: -> { Post.ids }
    )
```

**Comment by nickcharlton** [comment] 2020-03-31 21:16
Yes, I think that's a good solution.

@hudadiaz, does that work for you?

**Comment by nickcharlton** [comment] 2020-10-05 19:53
I'm going to close this as there's a solution above; if this doesn't work for you, please reopen it!

**Closed by nickcharlton** 2020-10-05 19:53 UTC
Labels: bug, fields
