### ISSUE TITLE
(Help) How to access current_user variable in the dashboard

### ISSUE THREAD

**Issue by rahulpattanshetty** [thoughtbot/administrate#2051] opened 2021-10-18 15:14 UTC
I'm using **Field::BelongsTo** where i need show only those records that belongs to the current user. Like below example
`Field::BelongsTo.with_options(scope: -> (field){ Theme.where(user_id: current_user.id) } )`

**Comment by pablobm** [comment] 2021-11-11 17:18
Unfortunately, this is not possible at the moment. The workaround would be to use [ActiveSupport::CurrentAttributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) to capture the current user and access it elsewhere. It's not a great solution, but it should work...? I haven't tried myself, so I can't guarantee.

For a bit more of discussion, see https://github.com/thoughtbot/administrate/issues/1593.

I'm going to close this issue as it's a duplicate of the linked one. Best to keep a single conversation around this.

**Closed by pablobm** 2021-11-11 17:18 UTC
