### ISSUE TITLE
Incomplete install script or directions

### ISSUE THREAD

**Issue by eclectic-coding** [thoughtbot/administrate#1871] opened 2021-01-17 22:46 UTC
* What were you trying to do?
Install administrate into a Rails app. 

* What versions are you running?
  - Rails v. 6.1
  - Ruby v. 3.0.0
  - administrate v. 0.14.0

I following the direction to install `administrate`, and used the generator as specified on the [Getting Started](https://administrate-demo.herokuapp.com/getting_started) page. However, when I migrate to the `admin` path, I get an error page. 

The problem is that the following needs to be added to the `app/assets/config/manifest.js`:
```
//= link administrate/application.css
//= link administrate/application.js
```
The [Getting Started](https://administrate-demo.herokuapp.com/getting_started) page needs to include this additional step, or the install generator needs to include this step. 

Please let me know if or how I can help to make this small item more seamless.
Thank you for a great product.

**Comment by pablobm** [comment] 2021-01-21 14:59
Oops. You are correct that this info is missing.

Fortunately, this problem is already "fixed", and you can see it in the prerelease documentation at https://administrate-demo-prerelease.herokuapp.com/getting_started. Now we need to publish a new version of the gem, and the documentation will be more clearly available. The root of the problem is that we have been slow to do so... :disappointed:

**Comment by nickcharlton** [comment] 2021-02-26 16:21
I'm going to close this now, but there will be a new release out today (2021-02-26) which will solve this properly.

**Closed by nickcharlton** 2021-02-26 16:21 UTC
Labels: bug
