### ISSUE TITLE
Inflection Issues on non-standard model names.

### ISSUE THREAD

**Issue by jersingh** [thoughtbot/administrate#393] opened 2016-01-09 00:15 UTC
We've got a model called DocumentData. Yes, it should be DocumentDatum but that just doesn't feel right.

Anyway, running the administrate generator throws this error:
uninitialized constant DocumentDatum (NameError)

Even with this inflection rule:
inflect.uncountable %w( DocumentData )
and adding --force-plural at the end of the administrate generator call.

We'd love to start using this on our project. Is there a way to get this to work with our non-standard model names?

Thanks,
Joe

**Comment by mjankowski** [comment] 2016-01-16 14:09
I believe that the generator is trying to pluralize a filename, but not going through Rails inflections for model names.  Can you provide the exact command you ran and exact output you see?

**Comment by tmecklem** [comment] 2016-01-17 01:24
I submitted a PR for this: https://github.com/thoughtbot/administrate/pull/414

**Comment by jersingh** [comment] 2016-01-17 04:10
Here's my command and output:

rails generate administrate:install

Running via Spring preloader in process 27312
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_manifest.rb
       route  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
      create  app/dashboards/definition_dashboard.rb
      create  app/controllers/admin/definitions_controller.rb
      create  app/dashboards/document_dashboard.rb
      create  app/controllers/admin/documents_controller.rb
      create  app/dashboards/document_datum_dashboard.rb
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:88:in
`const_get': uninitialized constant DocumentDatum (NameError)
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:88:in
`klass'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:41:in
`attributes'
        from (erb):11:in `template'
        from
/home/jersingh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from
/home/jersingh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in
`block in template'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in
`render'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in
`block (2 levels) in invoke!'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in
`open'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in
`block in invoke!'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in
`invoke_with_conflict_check'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in
`invoke!'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in
`action'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in
`create_file'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in
`template'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators/named_base.rb:26:in
`block in template'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators/named_base.rb:60:in
`inside_template'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators/named_base.rb:25:in
`template'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:28:in
`create_dashboard_definition'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
`run'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
`invoke_command'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`block in invoke_all'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`each'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`map'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`invoke_all'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in
`dispatch'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
`start'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:157:in
`invoke'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:29:in
`block in run_dashboard_generators'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in
`each'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in
`run_dashboard_generators'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
`run'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
`invoke_command'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`block in invoke_all'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`each'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`map'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in
`invoke_all'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in
`dispatch'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
`start'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:157:in
`invoke'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in
`<top (required)>'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:123:in
`require_command!'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:130:in
`generate_or_destroy'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in
`generate'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in
`run_command!'
        from
/home/jersingh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in
`<top (required)>'
        from /home/jersingh/projects/ruby/coi/bin/rails:8:in `<top
(required)>'
        from
/home/jersingh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from
/home/jersingh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from -e:1:in `<main>'

On Sat, Jan 16, 2016 at 6:24 PM, Tim Mecklem <notifications@github.com>
wrote:

> I submitted a PR for this: #414
> <https://github.com/thoughtbot/administrate/pull/414>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/administrate/issues/393#issuecomment-172282392>
> .
>



-- 
J

**Comment by tmecklem** [comment] 2016-01-25 13:23
#414 does not fix this issue. It only addresses the sidebar link_to index

**Comment by jalberto** [comment] 2016-04-21 16:05
Maybe related to #558 ?

**Comment by jalberto** [comment] 2016-05-12 11:51
@mjankowski can you check #558 ? PR attached (#559) it fix it for me

**Comment by jersingh** [comment] 2016-10-06 00:32
Still seeing this. Is there a fix for this yet?

I can move affected models out of models folder (I don't need Administrate to deal with the models that crash. If the generator could target specific models or ignore others, that would be really nice) as a workaround but still...

**Comment by jalberto** [comment] 2016-10-06 10:40
@jersingh #559 PR is ready to merge, but the project seem sunmantained, you can fork it, and merge it yourself

**Comment by thecalliopecrashed** [comment] 2019-05-20 19:14
Hm, I believe this is caused by the same issue as #167. I'll move the note about #559 over to that issue, so we can check if it still exists.

I'll close this as a duplicate.

**Closed by thecalliopecrashed** 2019-05-20 19:14 UTC
Labels: follow up
