### ISSUE TITLE
Possibility to have two or more instances of administrate in same rails app

### ISSUE THREAD

**Issue by inem** [thoughtbot/administrate#1847] opened 2020-12-18 13:15 UTC
I have several roles in my app. And instead of implementing permissions system I am considering to simply add multiple instances of administrate with different sets of functionality. For repeating logic I'd just reuse some service layer logic.

Currently [documentation for generators looks](https://administrate-demo-prerelease.herokuapp.com/customizing_page_views) like only one instance of administrate is possible. But maybe I am wrong.

**Comment by liang3404814** [comment] 2020-12-19 01:23
potential duplicate https://github.com/thoughtbot/administrate/issues/1764

**Comment by pablobm** [comment] 2021-01-14 14:50
I agree that this is a duplicate of https://github.com/thoughtbot/administrate/issues/1764. I'm closing, but please let us know if you think otherwise.

**Closed by pablobm** 2021-01-14 14:50 UTC
