### ISSUE TITLE
Namespace option does not allow plurals

### ISSUE THREAD

**Issue by amyin** [thoughtbot/administrate#1037] opened 2017-11-29 21:18 UTC
I want the custom namespace "ops" since I have Admin as a model name so the Admin module is not possible for me. When I run `rails generate administrate:routes --namespace ops` I get `Could not load generator "generators/administrate/routes/routes_generator". Error: uninitialized constant Op::ApplicationController` (the controller is Ops::ApplicationController). It would be great if the "s" was not stripped from the namespace. Thanks!

**Comment by dimascyriaco** [comment] 2017-12-03 18:30
You could try to disable the inflector rule with something like this:

```rb
# config/initializers/inflections.rb
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.uncountable %w{ ops }
end
```

**Comment by pmackay** [comment] 2018-01-30 11:00
I just hit this issue today - would this be a useful note to add to the docs?

**Comment by nickcharlton** [comment] 2018-03-02 18:05
Adding to the inflector is the right thing to do here (it's conventional Rails). I'd love to see a mention in the docs though, so someone can easily fix this in the future!

**Comment by steffansluis** [comment] 2020-12-18 16:49
Ran into this today, changing the inflection makes no sense for us as the namespace corresponds to an module `Things`, not a module `Thing`. I found the following works as a workaround:

```ruby
module Admin
  module Things
    class StuffsController < Admin::ApplicationController
      def resource_class
        ::Things::Stuff
      end

      def dashboard_class
        ::Things::StuffDashboard
      end
    end
  end
end
```

**Comment by khamusa** [comment] 2022-09-27 21:39
While @steffansluis' solution seems the most adequate workaround, I don't think it's a proper long-term solution for the future of the framework itself.

We have a few namespaces after admin that are plural by definition:
"Admin::Benefits::..."
"Admin::CustomForms::...

I believe the issue is caused by a simplification on this line

https://github.com/thoughtbot/administrate/blob/baa0ff652ed00b8fdcb719e194f86c4eb1347f89/lib/administrate/resource_resolver.rb#L37-L39

We are singularizing every intermediate namespace and the model class name as well, as opposed to Rails' conventions themselves.


For instance, given rails routes like these:

```
namespace :forms do
  resources :authors
end
```

We'd expect:

- A route `/forms/authors` for the controller's index action
- A controller under `controllers/forms/authors_controller.rb`
- A model under `models/forms/author.rb`

In fact, this is what we get if we use the rails scaffold generator (if we try stating the model name as plural, it even yields a warning):

![Screenshot from 2022-09-27 18-34-34](https://user-images.githubusercontent.com/1708578/192639995-ca83e001-1769-40fd-aeea-69ea4f64f797.png)

I believe something like this could do the trick:
```
def controller_path_parts
  (*result, last_path) = controller_path.split("/")[1..-1]
  result.push(last_path.singularize)
  
  result
end
```

Would you be willing to accept a PR proposing this change?

**Comment by pablobm** [comment] 2022-10-06 12:46
I think this should be now fixed by https://github.com/thoughtbot/administrate/pull/2261

**Closed by pablobm** 2022-10-06 12:46 UTC
Labels: bug, documentation, namespacing
