### ISSUE TITLE
TypeError in Admin::UsersController#index,  Admin is not a module

### ISSUE THREAD

**Issue by syafiqfaiz** [thoughtbot/administrate#226] opened 2015-11-12 05:10 UTC
Hi, I am trying to install Administrate for my app, and  I got this error when accessing the admin page.

I did ```$ rails generate administrate:install```

Am I missing any step?

**Comment by tute** [comment] 2015-11-12 05:29
Closing as duplicate of https://github.com/thoughtbot/administrate/issues/225. Thanks for reporting!

**Closed by tute** 2015-11-12 05:29 UTC
