### ISSUE TITLE
Sass::SyntaxError - File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by jersingh** [thoughtbot/administrate#664] opened 2016-10-06 00:29 UTC
Upgraded a rails app from 4.1.16 to 4.2.7.1. Worked through the issues to get it up and running.

Added administrate to Gemfile, and after running the generator and a puma reboot, getting stated error.

I'm loathe to include Gemfile.lock but will provide if requested.

**Comment by JoelQ** [comment] 2016-10-07 15:18
Could this be a duplicate of #615 ?

**Comment by pkoch** [comment] 2016-10-19 11:22
Looks like it. Close?

**Closed** 2016-10-19 16:37 UTC
Labels: bug, duplicate
