### ISSUE TITLE
NoMethodError in Admin::UsersController#index

### ISSUE THREAD

**Issue by aet08** [thoughtbot/administrate#1343] opened 2019-05-11 00:18 UTC
I have an existing rails app, I added the gem, ran rails generate administrate:install
went to http://localhost:3000/admin
and this happens, no idea how to trouble shoot.

NoMethodError in Admin::UsersController#index
undefined method `per' for #<User::ActiveRecord_Relation:0x000056546909bac8>
Extracted source (around line #125):
123            arel.public_send(method, *args, &block)
124          else
125            super
126          end
127        end
128    end
              

activerecord (5.2.3) lib/active_record/relation/delegation.rb:125:in `method_missing'
administrate (0.11.0) app/controllers/administrate/application_controller.rb:12:in `index'
actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.3) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.3) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.3) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.3) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.3) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.3) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Request
Parameters:

None

**Comment by navjeetc** [comment] 2019-05-12 03:35
Please post the code for User model and may be we can help.

**Comment by aet08** [comment] 2019-05-12 18:03
`class User < ApplicationRecord
  after_create :skip_conf!
  # Include default devise modules. Others available are:
  #   and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
  has_many :profiles

  
  def skip_conf!
    self.confirm if Rails.env.development?
  end
end
`

`module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end
`

**Comment by Adespinoza** [comment] 2019-07-23 18:22
I cleaned up the code for you @aet08: 
```ruby
class User < ApplicationRecord
after_create :skip_conf!
devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :validatable,
:confirmable, :lockable, :timeoutable, :trackable
has_many :profiles

 def skip_conf!
  self.confirm if Rails.env.development?
 end
end
```
```ruby
module Admin
 class UsersController < Admin::ApplicationController
 end
end
```

I previously had this issue while trying to call a User function within a different class, except with Pundit's `CurrentContext`. Not sure if you're doing something similar, but the `NoMethodError` is raised when the `per` method is called on a receiver which doesn't have it defined.

**Comment by BKSpurgeon** [comment] 2019-08-22 04:51
@aet08 can you please paste in the following file: app/controllers/administrate/application_controller.rb:12 (especially the index method and line 12).

See if you can spot the method `.per` being called? It should only be called on an object which can respond to `per`. Please advise.

**Comment by hellola** [comment] 2020-02-24 02:44
I had the same problem, the code was: 
```
      resources = order.apply(resources)
      resources = resources.page(params[:page]).per(records_per_page)
```
I remembered I have the `paginate` gem in my Gemfile, after removing it worked.

**Comment by pablobm** [comment] 2020-02-27 17:12
I had a look and I can confirm that there's an incompatibility with the [will_paginate](https://github.com/mislav/will_paginate) gem. (I couldn't reproduce with [paginate](https://github.com/fnando/paginate)).

This issue has been raised a few times, at least at https://github.com/thoughtbot/administrate/issues/158, https://github.com/thoughtbot/administrate/issues/284 and https://github.com/thoughtbot/administrate/issues/606 (check those for workarounds).

To solve this, we'll have to abstract the pagination code, potentially allowing usage with different providers of pagination. This might be a substantial piece of work though.

**Comment by BKSpurgeon** [comment] 2020-02-29 01:20
> I had a look and I can confirm that there's an incompatibility with the [will_paginate](https://github.com/mislav/will_paginate) gem. (I couldn't reproduce with [paginate](https://github.com/fnando/paginate)).
> 
> This issue has been raised a few times, at least at #158, #284 and #606 (check those for workarounds).
> 
> To solve this, we'll have to abstract the pagination code, potentially allowing usage with different providers of pagination. This might be a substantial piece of work though.

@pablobm 
What about a responds to method? And if no known pagination method then the unpaginated results are simply returned?

**Comment by pablobm** [comment] 2020-03-05 15:41
I'm not sure it's so simple. For one, this change would need to go in... I think two different places: the application controller and the has_many field. Then the `paginate` helper (used in two templates) would also need to be adapted. Not sure right now if there would be more to it.

Perhaps a PR could be created with a first, back-compatible solution, and we can generalise from there. Would you be up for it?

**Comment by nickcharlton** [comment] 2020-10-05 18:24
I'm going to close this as in the short-term we're not going to be looking at changing the pagination in a big way.

**Closed by nickcharlton** 2020-10-05 18:24 UTC
Labels: bug, dashboards, pagination
