### ISSUE TITLE
DateTime Field blank on edit

### ISSUE THREAD

**Issue by airjoshb** [thoughtbot/administrate#745] opened 2017-02-01 23:09 UTC
I know this has been an issue in the past, but I am having this problem currently v. 0.3.0 on rails 4.2, making it very difficult to update records as the field is blank every edit.

**Comment by stevenmilton58** [comment] 2017-03-09 05:46
@airjoshb I'm not seeing this issue on Rails 4.2.7.1 or Rails 5.0.2. Is this still an issue for you?

**Comment by airjoshb** [comment] 2017-03-09 17:32
Yes- I have to set the field on every edit as it is blank

**Comment by stevenmilton58** [comment] 2017-03-09 21:18
Questions: 

1 What is your exact rails version used? 
2. What browser are you using? 
3. Is the field still blank if you load the page with javascript disabled in your browser?

Can you provide steps to reproduce?

**Comment by airjoshb** [comment] 2017-04-08 18:37
Sorry for the long delay - I have been recovering from a major surgery

1. 3.2.1
2. Safari or Chrome
3. no, it seems to show up. Does this mean there is a js loading issue?

My application.js for administrate is 

`//= require jquery
//= require jquery_ujs
//= require selectize
//= require moment
//= require datetime_picker
//= require_tree .
`

**Comment by airjoshb** [comment] 2017-04-23 17:20
Any ideas how to fix?

**Comment by nickcharlton** [comment] 2017-12-01 12:18
Hi @airjoshb!

I hope you're all well and recovered now. It's been a little while since this was noticed. Is this still an issue you're having?

**Comment by airjoshb** [comment] 2017-12-01 19:57
Thanks for writing back - I recently updated to 0.8.1 and still had the issues, but after seeing your response, I went into my js file and shuffled things around. It is definitely a conflict between moment and datetime_picker as if I remove moment or call it above, it works. However if I move it above, moment doesn't work any longer.

**Comment by airjoshb** [comment] 2017-12-01 21:07
@nickcharlton after digging a bit further, when I removed the format settings from the administrate date_time_picker.js it all started working again

**Comment by nickcharlton** [comment] 2017-12-02 16:07
Ooh, that's interesting!

With the format string removed, does the previous ordering trick not make a difference either?

**Comment by airjoshb** [comment] 2017-12-04 22:07
Just removing/changing the format string solved the problem. Here is my current, which is working great 
`$(function () {
  $('.datetimepicker').datetimepicker({
    showTodayButton: true,
    format: 'LLL'
  });
});`

**Comment by nickcharlton** [comment] 2017-12-19 22:42
I haven't yet been able to look into this further, but do you have any thoughts on what might be a good fix to make to avoid this problem in the future?

If we remove the format string from administrate itself, I'd expect that to cause other problems. But perhaps there's a different way we could set it?

**Comment by airjoshb** [comment] 2017-12-21 17:31
It seems that it is just the way the format is being executed, as my, format: 'LLL', works fine

**Comment by nickcharlton** [comment] 2018-01-16 10:29
Oh, that's interesting to know. I'll give it some thought.

**Comment by nickcharlton** [comment] 2020-01-02 15:08
I'm going to close this as the last comment was a while ago and there's other issues relating to this field.

**Closed by nickcharlton** 2020-01-02 15:08 UTC
Labels: bug, fields
