### ISSUE TITLE
Customizing date_time field partials yields error

### ISSUE THREAD

**Issue by loumarven** [thoughtbot/administrate#1610] opened 2020-04-11 15:56 UTC
* What were you trying to do?
Customized date_time partials (index, show) with the following:
`<%= field.datetime.with_options(format: "%a, %-d %b %Y %l:%M:%S %p") %>`

* What did you end up with (logs, or, even better, example apps are great!)?
`undefined method 'arity' for nil:NilClass`

* What versions are you running?
  - Rails 5.2.4.2
  - administrate 0.13.0

I tried the format above in one of the dashboards and the format is valid, but I was hoping I could do it in the partials (as stated in http://administrate-prototype.herokuapp.com/customizing_attribute_partials) so I wouldn't have to do it on every dashboard.
Did I miss something in what I typed in the date_time partials?

Thank you!

**Comment by pablobm** [comment] 2020-04-18 17:36
The problem is that you cannot use the normal field options in the templates: they can only be used when defining the fields in the dashboards.

When you are in template land, you have an instance of the field (as `field`) with its specific value for that record (as `field.data`).

As you'll have seen, these field instances have a method `field.datetime`. That's a string representation of `field.data`. You can see the implementation at: https://github.com/thoughtbot/administrate/blob/fc57bb9c2755f0e49f9e0b5553e46420e6e15fce/lib/administrate/field/date_time.rb#L13-L19

A first way to achieve your aim would be to reproduce the body of this method in the templates, reading from `field.data` and rendering in your desired format. For example:

```erb
<% if field.data %>
  <%= I18n.localize(
    field.data.in_time_zone(
      field.options.fetch(:timezone, ::Time.zone.name || "UTC")
    ),
    format: "%a, %-d %b %Y %l:%M:%S %p",
    default: field.data,
  ) %>
<% end %>
```

Another alternative would be to create your field that inherits from `DateTime`, and overrides the `datetime` method with your desired formatting.

Something else that I'm thinking should work is to define your custom datetimes like this in an initializer:

```ruby
### /config/initializers/custom_fields.rb
FormattedDateTime = Administrate::Field::DateTime.with_options(format: "...")
```

Then use it in your dashboards:

```ruby
published_at: FormattedDateTime,
```

I'm going to close this for now, as I don't think it's a bug, but please let us know whether any of these options works for you.

**Closed by pablobm** 2020-04-18 17:36 UTC
Labels: bug, fields

**Comment by loumarven** [comment] 2020-04-18 22:48
Thank you for your help @pablobm!
Option 1 worked.
